import React, { useState, useContext } from "react";
import { Input, Button, Card } from "antd";
import axios from "axios";
import { AuthContext } from "../context/AuthContect";
import { toast } from "react-toastify";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";

const { TextArea } = Input;

const ResumeBuilder = () => {
  const { backend_Url } = useContext(AuthContext);

  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    education: "",
    experience: "",
    skills: "",
    projects: "",
  });

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [formVisible, setFormVisible] = useState(true);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const resetForm = () => {
    setFormData({
      name: "",
      email: "",
      phone: "",
      education: "",
      experience: "",
      skills: "",
      projects: "",
    });
    setFormVisible(false); // Hide form after submission
  };

  const generateResume = async () => {
    setLoading(true);
    try {
      const response = await axios.post(`${backend_Url}/api/career/generate`, formData);
      if (response.data.success) {
        setResult(response.data.result);
        resetForm();
      } else {
        toast.error("AI failed to generate your resume.");
      }
    } catch (err) {
      toast.error(err?.response?.data?.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto pt-6 px-0 sm:px-4">
      <div className="mb-4 text-center">
        <h1 className="text-[19px] sm:text-[26px]" style={{fontWeight: "600"}}>AI Resume Builder</h1>
        <p className="text-[13px] sm:text-[15px] text-gray-600">
          Fill the form and get a professional resume generated by AI.
        </p>
        {!formVisible && (
          <Button onClick={() => setFormVisible(true)} type="primary" className="mt-3">
            Edit Form
          </Button>
        )}
      </div>

      {formVisible && (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            generateResume();
          }}
        >
          <Card className="mb-3 shadow-sm p-2">
            <h2 className="text-lg font-semibold mb-3">👤 Personal Details</h2>
            <Input
              placeholder="Full Name"
              name="name"
              onChange={handleChange}
              value={formData.name}
              className="mb-2"
              required
            />
            <Input
              placeholder="Email Address"
              name="email"
              onChange={handleChange}
              value={formData.email}
              className="mb-2"
              required
            />
            <Input
              placeholder="Phone Number"
              name="phone"
              onChange={handleChange}
              value={formData.phone}
              className="mb-2"
              required
            />
          </Card>

          <Card className="mb-3 shadow-sm p-2">
            <h2 className="text-lg font-semibold mb-3">🎓 Education</h2>
            <TextArea
              rows={2}
              placeholder="Your Educational Background"
              name="education"
              onChange={handleChange}
              value={formData.education}
              className="mb-2"
              required
            />
          </Card>

          <Card className="mb-3 shadow-sm p-2">
            <h2 className="text-lg font-semibold mb-3">💼 Experience & Skills</h2>
            <TextArea
              rows={2}
              placeholder="Work Experience (if any)"
              name="experience"
              onChange={handleChange}
              value={formData.experience}
              className="mb-2"
              required
            />
            <TextArea
              rows={2}
              placeholder="Skills (e.g., React, JavaScript, Node.js)"
              name="skills"
              onChange={handleChange}
              value={formData.skills}
              className="mb-2"
              required
            />
          </Card>

          <Card className="mb-3 shadow-sm p-2">
            <h2 className="text-lg font-semibold mb-3">🛠️ Projects</h2>
            <TextArea
              rows={2}
              placeholder="Project titles and short descriptions"
              name="projects"
              onChange={handleChange}
              value={formData.projects}
              className="mb-2"
              required
            />
          </Card>

          <div className="flex justify-end">
            <Button
              htmlType="submit"
              type="primary"
              loading={loading}
              className="px-6 w-full sm:w-auto"
              style={{ height: "44px" }}
            >
              Generate Resume
            </Button>
          </div>
        </form>
      )}

      {result && (
        <div className="mt-8 bg-blue-50 border border-blue-200 shadow-md rounded-xl">
          <Card
            title={<div className="text-[20px] font-bold text-blue-700">📄 AI-Generated Resume</div>}
            bordered={false}
            className="bg-transparent"
            bodyStyle={{ padding: "1.25rem" }}
          >
            <div className="prose max-w-full text-base prose-blue whitespace-pre-wrap">
              <ReactMarkdown
                children={result}
                remarkPlugins={[remarkGfm]}
                rehypePlugins={[rehypeRaw]}
                components={{
                  p: ({ node, ...props }) => <p className="mb-3 leading-relaxed" {...props} />,
                  li: ({ node, ...props }) => <li className="mb-1" {...props} />,
                }}
              />
            </div>
          </Card>
        </div>
      )}
    </div>
  );
};

export default ResumeBuilder;
